# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aeed06e72a80efe4ed75d989b8ded19078856920018b640a28ade1ad222468e824fc2e19d3d8d1b43650fe8cb43ece4b7a19698f59e8a200fefa8effc729b43e

test:
  secret_key_base: 37c310fbc5cf360fbd5e8e4737a45f15029f173b411180e2c6eaf0de026bdf7acdc2f540ba01c5da6bf2f2df2b6e68454a41001c4a8f74839b50b98e43f9a72b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
